language: python
sudo: required

services:
  - docker

before_install:
  - pip install ansible==2.6.1

script:
  - pwd
  - ansible-playbook -i tests/inventory tests/test.yml
  - pwd
  - ansible-playbook -i tests/cluster_inventory tests/test-role.yml
