language: python
sudo: required

services:
  - docker

before_install:
  - pip install ansible==2.6.1
  - pip install lxc-python2

script:
  - ansible-playbook -i tests/inventory tests/test.yml
  - ansible-playbook -i tests/cluster_inventory tests/test_role.yml
